name: Auto Sync Fork

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # 每天 00:00 执行

jobs:
  sync_fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Fetch Upstream
        env:
          SOURCE_REPO: bestZwei/LibreTV # 替换为你的上游仓库
          LIBRETV_TOKEN: ${{ secrets.LIBRETV_TOKEN }} # 替换为你的上游仓库token，如果不需要可以删除这个secret
        run: |
          git remote add upstream "https://github.com/${{ env.SOURCE_REPO }}.git"
          git fetch upstream
          # 如果你的上游仓库需要身份验证，请取消注释以下行，并替换为你的令牌
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n :${{ env.LIBRETV_TOKEN }} | base64)" # 添加身份验证

      - name: Merge Upstream Changes (Theirs Strategy)
        run: |
          git checkout main # 切换到你的主分支 (例如 main 或 master)
          git merge -X theirs upstream/main # 使用 -X theirs 策略合并上游更改
          git push origin main # 推送到你的主分支
