name: Auto Sync Fork

on:
  workflow_dispatch:
  schedule:
#    - cron: '0 0 * * *' # 每天 00:00 执行

jobs:
  sync_fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取所有历史记录

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Fetch Upstream
        env:
          SOURCE_REPO: bestZwei/LibreTV # 替换为你的上游仓库
          LIBRETV_TOKEN: ${{ secrets.LIBRETV_TOKEN }} # 替换为你的上游仓库token，如果不需要可以删除这个secret
        run: |
          git remote add upstream "https://github.com/${{ env.SOURCE_REPO }}.git"
          git fetch upstream
          # 如果你的上游仓库需要身份验证，请取消注释以下行，并替换为你的令牌
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n :${{ env.LIBRETV_TOKEN }} | base64)" # 添加身份验证

      - name: Attempt Merge
        run: |
          git checkout main
          git merge upstream/main
        continue-on-error: true # 允许这一步失败

      - name: Reset and Force Push (if merge failed)
        if: steps.Attempt_Merge.outcome == 'failure'
        run: |
          git checkout main # 切换到你的主分支 (例如 main 或 master)
          git reset --hard upstream/main # 强制将本地分支重置为上游分支
          git push origin main --force # 强制推送本地更改到远程仓库 (请谨慎使用 --force)
