name: Auto Sync Fork

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync_fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Fetch Upstream
        env:
          SOURCE_REPO: bestZwei/LibreTV
          LIBRETV_TOKEN: ${{ secrets.LIBRETV_TOKEN }}
        run: |
          git remote add upstream "https://github.com/${{ env.SOURCE_REPO }}.git"
          git fetch upstream
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n :${{ env.LIBRETV_TOKEN }} | base64)" # 添加身份验证

      - name: Merge Upstream Changes
        id: Merge_Upstream_Changes
        run: |
          git checkout main # 切换到你的主分支 (例如 main 或 master)
          git merge --allow-unrelated-histories upstream/main # 添加 --allow-unrelated-histories
          echo "::set-output name=has_changes::$(git status --porcelain)" # 检查是否有更改

      - name: Push Changes to Fork
        if: steps.Merge_Upstream_Changes.outputs.has_changes != ''
        run: |
          git push origin main # 推送到你的主分支
          echo "Changes pushed to fork."
